name: Validate Justfiles
permissions:
  contents: read

on:
  pull_request:
    paths:
      - "custom/ujust/**"
      - "Justfile"
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v5

      - name: Install just
        uses: extractions/setup-just@dd310ad5a97d8e7b41793f8ef055398d51ad4de6 # v2

      - name: Validate Justfiles
        shell: bash
        run: |
          echo "Validating justfiles in custom/ujust/ directory..."

          set -xeuo pipefail

          # Validate root Justfile
          echo "::group:: Validating Justfile"
          just --unstable --fmt --check -f Justfile
          echo "::endgroup::"

          # Validate custom ujust files
          find "custom/ujust" -iname '*.just' -print0 | \
            while IFS= read -r -d '' justfile ; do \
              echo "::group:: ===$(basename "$justfile")==="
              just --unstable --fmt --check -f "$justfile"
              echo "::endgroup::"
            done

          echo "All justfiles are valid"
